PostaniFerovac2/PostaniFerovac2/Models/Test.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PostaniFerovac2.Models
{
    public class Test
    {
        public int testId { get; set; }
        
        public string user { get; set; }
        public int brojPitanja { get; set; }
        public int tocnih { get; set; }
        public int vrijeme { get; set; }
        public DateTime? datum { get; set; }
        public List<TestZadatak> testZadaci { get; set; }
        public int bodovi { get; set; }
        public string username;
        public int predmetId;
    }
}

PostaniFerovac2/PostaniFerovac2/Controllers/TestController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PostaniFerovac2.Models;

namespace PostaniFerovac2.Controllers
{
    public class TestController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Test
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Start(int? brojPitanja)
        {
            string tip = "na";
            if (tip.Equals("Fizika"))
            {
                // ocitavaj iz fizikalnih
            }
            else if (tip.Equals("Matematika"))
            {
                // ocitavaj iz matematickih zadataka
            }
            int max = 4; // ovo ce poprimiti vrijednost broja zadataka u toj skupini, 4 placeholder
            List<Zadatak> zadaci = new List<Zadatak>();
            while (brojPitanja >= 0)
            {
                Zadatak zadatak = db.zadaci.Find(generateRandomId(max));
                if (zadatak == null)
                {
                    return HttpNotFound();
                }
                zadaci.Add(zadatak);
                brojPitanja--;
            }
            return View(zadaci);
        }

        private Int32 generateRandomId(int max)
        {
            Random rnd = new Random();
            return rnd.Next(max);
        }

        private ActionResult CountTime()
        {
            Stopwatch sw = new Stopwatch(); // mjerimo vrijeme po testu

            sw.Start();

            // ...

            int limit = 60;
            if (sw.Elapsed.Equals(limit))
            {
                sw.Stop();
                Console.WriteLine("Elapsed={0}", sw.Elapsed);
                return View();
            }
            return null;

        }
    }
}

PostaniFerovac2/PostaniFerovac2/Controllers/TestsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Diagnostics;
using System.Linq;
using System.Net;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using PostaniFerovac2.Models;
using Microsoft.AspNet.Identity;

namespace PostaniFerovac2.Controllers
{
    [HandleError]
    public class TestsController : Controller
    {
        Test test = new Test();
        private static Int32 konstBrojPitanja = 10;    // 10 po dogovoru
        private Int32 brojPrikazanih = 20;
        Random rnd = new Random();
        private ApplicationDbContext db = new ApplicationDbContext();
        

        // GET: Tests
        public ActionResult Index()
        {
            if (!Request.IsAuthenticated)
            {
                return RedirectToAction("Index", "Home");
            }
            string identity = User.Identity.GetUserId();
            List<Test> tests = db.Tests.Where( t => t.user == identity ).ToList();
            List<String> subjects = new List<string>();
            foreach (Test t in tests)
            {
                // generirati listu ispita
                subjects.Add(dohvatiNazivPredmeta(t));
            }
            Tuple<IEnumerable<Test>, IEnumerable<string>> tuple = new Tuple<IEnumerable<Test>, IEnumerable<string>>(tests,subjects);
            return View(tuple);
        }

        // GET: Tests/Details/5
        public ActionResult Details(int? id)
        {
            if (!Request.IsAuthenticated)
            {
                return RedirectToAction("Index", "Home");
            }
            int uId;    // ovo bude korisnicki id
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            else
            {
                uId = (int)id;
            }
            Test dummy = db.Tests.Where(o => o.testId == uId).First();
            /*dummy.user = User.Identity.GetUserId();
            dummy.testId = uId;*/

            List<TestZadatak> testZadaci = db.TestZadataks.Where(o => o.testId == id).ToList();
            /*if (test == null)
            {
                return HttpNotFound();
            }*/
            List<Zadatak> zadaci = new List<Zadatak>();
            foreach (TestZadatak tz in testZadaci)
            {
                zadaci.Add(db.zadaci.Where(o => o.zadatakId == tz.zadatakId).Single());
            }
            ViewBag.Predmet = dohvatiNazivPredmeta(dummy);
            Tuple<Test, IEnumerable<Zadatak>> tuple = new Tuple<Test, IEnumerable<Zadatak>>(dummy, zadaci);
            return View(tuple);
        }

        // GET: Tests/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(int? predmet)
        {
            if (!Request.IsAuthenticated)   // onemoguci pristup neregistriranim korisnicima
            {
                return RedirectToAction("Index", "Home");
            }
            Test test = new Test();
            test.brojPitanja = 10;  // default postavljanje na 10
            try
            {
                test.predmetId = (int)predmet;
            }
            catch (InvalidOperationException ioe)
            {
                ;   // ovdje napraviti kaj bude se radilo ako nije zadan predmet
            }
            return View(test);
        }

        // POST: Tests/Create
        public ActionResult Create([Bind(Include = "testId,userId,brojPitanja")] Test test, int? predmet)
        {
            if (!Request.IsAuthenticated)
            {
                return RedirectToAction("Index", "Home");
            }
            test.brojPitanja = 10;
            try
            {
                test.predmetId = (int)predmet;
            }
            catch (InvalidOperationException ioe)
            {
                ;   // ovdje napraviti kaj bude se radilo ako nije zadan predmet
            }
            return View(test);
        }

        // GET: Tests/Edit/5
        public ActionResult Edit(int? id)
        {
            if (!Request.IsAuthenticated)
            {
                return RedirectToAction("Index", "Home");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Test test = db.Tests.Find(id);
            if (test == null)
            {
                return HttpNotFound();
            }
            return View(test);
        }

        // POST: Tests/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "testId,userId,brojPitanja")] Test test)
        {
            if (!Request.IsAuthenticated)
            {
                return RedirectToAction("Index", "Home");
            }
            if (ModelState.IsValid)
            {
                db.Entry(test).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(test);
        }

        // GET: Tests/Delete/5
        public ActionResult Delete(int? id)
        {
            if (!Request.IsAuthenticated)
            {
                return RedirectToAction("Index", "Home");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Test test = db.Tests.Find(id);
            if (test == null)
            {
                return HttpNotFound();
            }
            return View(test);
        }

        // POST: Tests/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if (!Request.IsAuthenticated)
            {
                return RedirectToAction("Index", "Home");
            }
            Test test = db.Tests.Find(id);
            db.Tests.Remove(test);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult Leaderboard(int predmet = 0, int bracket = 0)
        {
            if (!Request.IsAuthenticated)
            {
                return RedirectToAction("Index", "Home");
            }
            List<Test> tests = poredakTestova(predmet, bracket);

            foreach (Test t in tests)
            {
                if(db.Users.Where(c => c.Id.Equals(t.user)).FirstOrDefault() != null)
                {
                    t.username = db.Users.Where(c => c.Id.Equals(t.user)).First().UserName;
                }
            }
            List<String> subjects = new List<string>();
            foreach (Test t in tests)
            {
                if (db.Users.Where(c => c.Id.Equals(t.user)).FirstOrDefault() != null)
                {
                    subjects.Add(dohvatiNazivPredmeta(t));
                }               
            }
            Tuple<IEnumerable<Test>, IEnumerable<string>, int, int> tuple = new Tuple<IEnumerable<Test>, IEnumerable<string>, int, int>(tests.Take(brojPrikazanih), subjects, predmet, bracket);
            return View(tuple);
        }

        [HttpPost]
        public ActionResult Start(int? predmet,int? brojPitanja)
        {
            if (!Request.IsAuthenticated)
            {
                return RedirectToAction("Index", "Home");
            }
            if (predmet == null)    // predmet nije zadan, javi error
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            List<Zadatak> zadaci = new List<Zadatak>();
            List<Zadatak> povratni = new List<Zadatak>();
            zadaci = db.zadaci.Include(z => z.cjelina).Include(z => z.statistikaDM).Where(z => z.cjelina.predmetId==predmet).ToList();
            int max = zadaci.Count; // broj zadataka u skupini
            int pitanja = konstBrojPitanja;
            if (brojPitanja != null)
            {
                pitanja = (int)brojPitanja;
            }
            int duplicatePitanja = pitanja;
            List<Int32> ids = new List<int>();
            List<String> napomene = new List<string>();
            while (pitanja > 0)
            {
                Zadatak zadatak = zadaci[getNextId(ids,max)];
                if (zadatak == null)
                {
                    return HttpNotFound();
                }
                povratni.Add(zadatak);
                pitanja--;
            }

            Session["Rem_Time"] = DateTime.Now.AddMinutes(duplicatePitanja*3).ToUniversalTime().ToString("dd-MM-yyyy H:mm:ss");
            ViewBag.Message = "Test je gotov.";
            ViewBag.EndDate = Session["Rem_Time"];

            test.brojPitanja = duplicatePitanja;
            test.testZadaci = generateTestZadatak(povratni);
            napomene = generateNapomene(povratni);
            test.user = User.Identity.GetUserId();
            test.datum = DateTime.Now;
            test.vrijeme = 0;
            test.bodovi = 0;
            Tuple<Test, IEnumerable<string>> tuple;
            tuple = new Tuple<Test, IEnumerable<string>>(test, napomene);
            return View(tuple);
        }

        private List<string> generateNapomene(List<Zadatak> povratni)
        {
            List<string> napomene = new List<string>();
            foreach (Zadatak zad in povratni)
            {
                napomene.Add(zad.napomena);
            }
            return napomene;
        }

        private List<TestZadatak> generateTestZadatak(List<Zadatak> zadaci)
        {

PostaniFerovac2/PostaniFerovac2/Views/Tests/Create.cshtml
@model PostaniFerovac2.Models.Test

@{
    ViewBag.Title = "Pokreni test"; 
}

<div class="unutarnjiPadding">
    <h1 >Novi ispit</h1>
    @if (Model.predmetId == 1)
    {
        <h2>Matematika</h2>
        <p><a class="btn btn-default" href="http://dokumenti.ncvvo.hr/Ispitni_katalozi_08-09/Ispiti/mat_visa_for.pdf" target="_blank">Podsjetnik &raquo;</a></p>
    }
    else if (Model.predmetId == 2)
    {
        <h2>Fizika</h2>
        <p><a class="btn btn-default" href="http://dokumenti.ncvvo.hr/Ispitni_katalozi_12-13/Dodatci/formule_fiz.pdf" target="_blank">Podsjetnik &raquo;</a></p>
    }
    else if (Model.predmetId == 3)
    {
        <h2>Programiranje</h2>
    }
    else
    {
        <h2>Predmet još nije odabran!</h2>
    }
    @if (Model.predmetId == 3)
    {
        <p style="text-align: justify;">Ispit iz ovog predmeta može se pisati u samo jednoj varijanti od 5 pitanja.</p>
    }
    else
    {
        <p style="text-align: justify;">Podesi postavke ispita.</p>
        <p style="text-align: justify;">U ovisnosti o broju odabranih pitanja, bit će određeno vrijeme, a na tebi je samo da na čim više pitanja točno odgovoriš!</p>
    }
   
    @using (Html.BeginForm("Start", "Tests"))
    {
        @Html.AntiForgeryToken()
        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @if (Model.predmetId == 0)
            {
                <div class="form-group">
                    @Html.LabelFor(model => model.predmetId, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.predmetId, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.predmetId, "", new { @class = "text-danger" })
                    </div>
                </div>
            }
            else
            {
                @Html.Hidden("predmet", Model.predmetId)
            }
            <div class="form-group" >
            @if (Model.predmetId == 0 || Model.predmetId == 1 || Model.predmetId == 2)
            {
                <div class = "control-label col-md-2" >
                    <strong>Broj pitanja</strong>
                </div>
                <div class="col-md-2" >
                    @Html.EditorFor(model => model.brojPitanja, new { htmlAttributes = new { @class = "form-control", min = 3, max = 30 } })
                    @Html.ValidationMessageFor(model => model.brojPitanja, "", new { @class = "text-danger" })
                </div>
            }
            else
            {
                @Html.Hidden("brojPitanja", 5)
            }
            </div>
            <div class="form-group" >
                <div class="col-md-offset-2 col-md-10"  >
                    <input type="submit" value="Započni ispit!" class="btn zapocniIspit" />
                </div>
            </div>
        </div>
    }
    <div>
        @Html.ActionLink("Povratak", "Index")
    </div>
</div>

PostaniFerovac2/PostaniFerovac2/Views/Tests/Delete.cshtml
@model PostaniFerovac2.Models.Test

@{
    ViewBag.Title = "Delete";
}

<h3 style="padding-top:50px">Jeste li sigurni da želite obrisati ovaj ispit?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.Label("Broj pitanja: ")
        </dt>
        <dd>
            @Html.DisplayFor(model => model.brojPitanja)
        </dd>

        <dt>
            @Html.Label("Broj točnih odgovora: ")
        </dt>
        <dd>
            @Html.DisplayFor(model => model.tocnih)
        </dd>

        <dt>
            @Html.Label("Vrijeme ispitivanja: ")
        </dt>
        <dd>
            @Html.DisplayFor(model => model.vrijeme) sek
        </dd>

        <dt>
            @Html.Label("Broj bodova: ")
        </dt>
        <dd>
            @Html.DisplayFor(model => model.bodovi)
        </dd>
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Obriši" class="btn btn-default" /> |
            @Html.ActionLink("Povratak", "Index")
        </div>
    }
</div>

PostaniFerovac2/PostaniFerovac2/Views/Tests/Index.cshtml
@model Tuple<IEnumerable<PostaniFerovac2.Models.Test>,IEnumerable<string>>

@{
    ViewBag.Title = "Moji testovi";
}

<style>
    /* Sortable tables */
table.sortable thead {
    cursor: pointer;
}
table.sortable {
  max-width: 100%;
  background-color: transparent;
  width: 100%;
  margin-bottom: 20px;
  table-layout: fixed;
}
table.sortable thead > tr > th,
table.sortable tbody > tr > th,
table.sortable tfoot > tr > th,
table.sortable thead > tr > td,
table.sortable tbody > tr > td,
table.sortable tfoot > tr > td {
  padding: 8px;
  line-height: 1.428571429;
  vertical-align: top;
  border-top: 1px solid #dddddd;
}
table.sortable thead > tr > th {
  vertical-align: bottom;
  border-bottom: 2px solid #dddddd;
}
</style>

<head>
    <script src="http://www.kryogenix.org/code/browser/sorttable/sorttable.js"></script>
</head>

<h1 style="padding-top:50px">Ispiti korisnika <em>@User.Identity.Name</em></h1>

<br />
<dl class="dl-horizontal">
    <dt style="font-size:20px; padding-top:5px">
        @Html.Label("Novi ispit:")
    </dt>
    <dd>
        <div class="col-sm-10 row container">
            @using (Html.BeginForm("Create", "Tests", new { predmet = 1 }))
            {
                @Html.AntiForgeryToken()
                <div class="col-sm-3">
                    <button type="submit" style="font-size:17px;" class="btn daljeButton">Matematika</button>
                </div>
            }
            @using (Html.BeginForm("Create", "Tests", new { predmet = 2 }))
            {
                @Html.AntiForgeryToken()
                <div class="col-sm-3">
                    <button type="submit" style="font-size:17px" class="btn daljeButton">Fizika</button>
                </div>
            }
            @using (Html.BeginForm("Create", "Tests", new { predmet = 3 }))
            {
                @Html.AntiForgeryToken()
                <div class="col-sm-3">
                    <button type="submit" style="font-size:17px" class="btn daljeButton">Programiranje</button>
                </div>
            }
        </div>
    </dd>
</dl>

<table class="sortable" >
    <tr>
        <th style="width: 6em" class="tablicaIspitiGore">
            Broj
        </th>
        <th style="width: 15em; background-color:#6F7075; color:white;" class="sorttable_numeric">
            Datum
        </th>
        <th style="width: 10em" class="tablicaIspitiGore">
            Predmet
        </th>
        <th style="width: 10em" class="tablicaIspitiGore">
            Rješenost
        </th>
        <th style="width: 15em; background-color:#6F7075; color:white;" class="sorttable_numeric">
            Vrijeme
        </th>
        <th style="width: 9em" class="tablicaIspitiGore" title="Bodovi se računaju prema sljedećoj formuli: Postotak_rješenosti * Broj_točnih_odgovora">
            Bodovi
        </th>
        <th style="width: 12em" class="tablicaIspitiGore"></th>
    </tr> 
@{ 
    int i = 0;
    int j = 0;
    int k;
    int h;
    int min;
    int sec;
    string print;
    string datumkey;
    string day;
    string time;
    string sati;
    string vrijemekey;
    string vrijememin;
    string vrijemesec;
    string rjesenost1;
    string rjesenost2;
}
@foreach (var item in Model.Item1) {
    i = 0;
    foreach (var item2 in Model.Item2) {
        if (i == j)
        {
            k = i + 1;
            h = item.vrijeme / 3600;
            min = (item.vrijeme - (h * 3600)) / 60;
            sec = item.vrijeme % 60;
            day = item.datum.ToString().Split(' ')[0];
            time = item.datum.ToString().Split(' ')[1];
            sati = time.Split(':')[0];
            if (sati.Length == 1)
            {
                sati = "0" + sati;
            }
            if (day.Contains("."))
            {
                datumkey = day.Split('.')[0] + day.Split('.')[1] + day.Split('.')[2] + sati + time.Split(':')[1] + time.Split(':')[2];
            }
            else
            {
                datumkey = day.Split('/')[0] + day.Split('/')[1] + day.Split('/')[2] + sati + time.Split(':')[1] + time.Split(':')[2];
            }
            vrijememin = @min.ToString();
            vrijemesec = @sec.ToString();
            if (h != 0)
                print = h.ToString() + " sati " + vrijememin + " min " + vrijemesec + " sek";
            else if (h == 0 && min != 0)
                print = vrijememin + " min " + vrijemesec + " sek";
            else
                print = vrijemesec + " sek";
            if (vrijememin.Length == 1)
                vrijememin = "0" + vrijememin;
            if (vrijemesec.Length == 1)
                vrijemesec = "0" + vrijemesec;
            vrijemekey = h.ToString() + vrijememin + vrijemesec;

            rjesenost1 = item.tocnih.ToString();
            rjesenost2 = (100 - item.brojPitanja).ToString();
            if (rjesenost1.Length == 1)
                rjesenost1 = "0" + rjesenost1;
            <tr class="tablicaIspitiDolje">
                <td >
                    @k.
                </td>
                <td sorttable_customkey="@datumkey">
                    @Html.DisplayFor(model => item.datum)
                </td>
                <td>
                    @Html.DisplayFor(model => item2)
                </td>
                <td sorttable_customkey="@rjesenost1+@rjesenost2">
                    @Html.DisplayFor(model => item.tocnih)/@Html.DisplayFor(model => item.brojPitanja)
                </td>
                <td sorttable_customkey="@vrijemekey">
                    @Html.DisplayFor(model => print)
                </td>
                <td>
                    <strong>@Html.DisplayFor(model => item.bodovi)</strong>
                </td>
                <td>
                    @Html.ActionLink("Detalji", "Details", new { id = item.testId })
                    &nbsp&nbsp&nbsp
                    @Html.ActionLink("Obriši", "Delete", new { id = item.testId })
                    
                </td>
            </tr>
        }
        i++;
    }
    j++;
}
</table>

PostaniFerovac2/PostaniFerovac2/Views/Tests/Leaderboard.cshtml
@model Tuple<IEnumerable<PostaniFerovac2.Models.Test>, IEnumerable<string>, int, int>


@{
    ViewBag.Title = "Poredak";
}

<style>
    .col-sm-10 {
    width: 88%;
  }
</style>

<h1 style="padding-top:5%">Poredak</h1>

<dl class="dl-horizontal" style="padding-top:2em">
    <dt>
        @Html.Label("Filtriraj po predmetima:")
    </dt>
    <dd>
        <div class="col-md-8 row container">
            @using (Html.BeginForm("Leaderboard", "Tests", new { predmet = 0, bracket = Model.Item4 }))
            {
                if (Model.Item3 == 0)
                {
                    <div class="col-md-3">
                        <button type="submit" class="btn daljeButton" style="background-color: #BD102E">Svi predmeti</button>
                    </div>
                }
                else
                {
                    <div class="col-md-3">
                        <button type="submit" class="btn daljeButton">Svi predmeti</button>
                    </div>
                }
            }
            @using (Html.BeginForm("Leaderboard", "Tests", new { predmet = 1, bracket = Model.Item4 }))
            {
                if (Model.Item3 == 1)
                {
                    <div class="col-md-3">
                        <button type="submit" class="btn daljeButton" style="background-color: #BD102E">Matematika</button>
                    </div>
                }
                else
                {
                    <div class="col-md-3">
                        <button type="submit" class="btn daljeButton">Matematika</button>
                    </div>
                }
            }
            @using (Html.BeginForm("Leaderboard", "Tests", new { predmet = 2, bracket = Model.Item4 }))
            {
                if (Model.Item3 == 2)
                {
                    <div class="col-md-3">
                        <button type="submit" class="btn daljeButton" style="background-color: #BD102E">Fizika</button>
                    </div>
                }
                else
                {
                    <div class="col-md-3">
                        <button type="submit" class="btn daljeButton">Fizika</button>
                    </div>
                }
            }
            @using (Html.BeginForm("Leaderboard", "Tests", new { predmet = 3, bracket = Model.Item4 }))
            {
                if (Model.Item3 == 3)
                {
                    <div class="col-md-3">
                        <button type="submit" class="btn daljeButton" style="background-color: #BD102E">Programiranje</button>
                    </div>
                }
                else
                {
                    <div class="col-md-3">
                        <button type="submit" class="btn daljeButton">Programiranje</button>
                    </div>
                }
            }
        </div>
    </dd>
</dl>

<dl class="dl-horizontal">
    <dt>
        @Html.Label("Filtriraj po broju zadataka:")
    </dt>
    <dd>
        <div class="col-md-8 row container">
            @using (Html.BeginForm("Leaderboard", "Tests", new { predmet = Model.Item3, bracket = 0 }))
            {
                if (Model.Item4 == 0)
                {
                    <div class="col-md-3">
                        <button type="submit" class="btn daljeButton" style="background-color: #BD102E">ukupno</button>
                    </div>
                }
                else
                {
                    <div class="col-md-3">
                        <button type="submit" class="btn daljeButton">ukupno</button>
                    </div>
                }
            }
            @using (Html.BeginForm("Leaderboard", "Tests", new { predmet = Model.Item3, bracket = 1 }))
            {
                if (Model.Item4 == 1)
                {
                    <div class="col-md-3">
                        <button type="submit" class="btn daljeButton" style="background-color: #BD102E">manje od 10</button>
                    </div>
                }
                else
                {
                    <div class="col-md-3">
                        <button type="submit" class="btn daljeButton">manje od 10</button>
                    </div>
                }
            }
            @using (Html.BeginForm("Leaderboard", "Tests", new { predmet = Model.Item3, bracket = 2 }))
            {
                if (Model.Item4 == 2)
                {
                    <div class="col-md-3">
                        <button type="submit" class="btn daljeButton" style="background-color: #BD102E">10 do 20</button>
                    </div>
                }
                else
                {
                    <div class="col-md-3">
                        <button type="submit" class="btn daljeButton">10 do 20</button>
                    </div>
                }
            }
            @using (Html.BeginForm("Leaderboard", "Tests", new { predmet = Model.Item3, bracket = 3 }))
            {
                if (Model.Item4 == 3)
                {
                    <div class="col-md-3">
                        <button type="submit" class="btn daljeButton" style="background-color: #BD102E">više od 20</button>
                    </div>
                }
                else
                {
                    <div class="col-md-3">
                        <button type="submit" class="btn daljeButton">više od 20</button>
                    </div>
                }
            }
        </div>
    </dd>
</dl>

<br />

@if (Model.Item1.Count() == 0)
{
    <p><strong>Nisu rješavani testovi za trenutni upit.</strong></p>
}
else
{
    <table class="table">
        <tr></tr>
        <tr class="tablicaIspitiGore">
            <th>Položaj</th>
            <th>Datum</th>
            <th>Korisnik
            <th>Predmet</th>
            <th>Točnost</th>
            <th>Postotak</th>
            <th>Trajanje</th>
            <th title="Bodovi se računaju prema sljedećoj formuli: Postotak_rješenosti * Broj_točnih_odgovora" style="cursor:help">Bodovi</th>
        </tr>
        @{
            int i = 0;
            int j = 0;
            int k;
            int min;
            int sec;
            double postotak;
            int postotak2;
        }
        @foreach (var item in Model.Item1)
        {
            i = 0;
            foreach (var item2 in Model.Item2)
            {
                if (i == j)
                {
                    k = i + 1;
                    min = item.vrijeme / 60;
                    sec = item.vrijeme % 60;
                    postotak = item.tocnih;
                    postotak /= item.brojPitanja;
                    postotak2 = (int)(postotak * 100);
                    <tr class="tablicaIspitiDolje">
                        <td>
                            @k.
                        </td>
                        <td>
                            @Html.DisplayFor(model => item.datum)
                        </td>
                        <td>
                            @Html.DisplayFor(model => item.username)
                        </td>
                        <td>
                            @Html.DisplayFor(model => item2)
                        <td>
                            @Html.DisplayFor(model => item.tocnih)/@Html.DisplayFor(model => item.brojPitanja)
                        </td>
                        <td>
                            @Html.DisplayFor(model => postotak2)
                            %
                        </td>
                        <td>
                            @if (min != 0)
                            {
                                @Html.DisplayFor(model => min)
                                <h7>min</h7>
                            }
                            @Html.DisplayFor(model => sec)
                            sek
                        </td>
                        <td>
                            <strong>@Html.DisplayFor(model => item.bodovi)</strong>
                        </td>
                    </tr>
                }
                i++;
            }
            j++;
        }
    </table>
}